language: python
python:
  - "2.7"

install:
    - pip install git+https://github.com/digi604/django-smart-selects.git@eea07eeb759f75c77497b2425b84574cf6c6ac4d
    - pip install -r requirements.txt
    - pip install coveralls unittest2
before_script:
  - mv gestorpsi/settings.py.TRAVIS gestorpsi/settings.py

script:
  - python manage.py test client

after_script:
    - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/87309c799eae69dfdbbc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
